# Generated by Django 6.0.4 on 2026-05-07 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucChungChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('NGOAI_NGU', 'Chuẩn đầu ra Ngoại ngữ'), ('TIN_HOC', 'Chuẩn đầu ra Tin học')], max_length=20, verbose_name='Phân loại')),
                ('ten_chung_chi', models.CharField(help_text='VD: IELTS, TOEIC, MOS Word...', max_length=150, unique=True, verbose_name='Tên chứng chỉ')),
            ],
            options={
                'verbose_name': 'Danh mục Chứng chỉ',
                'verbose_name_plural': 'Danh mục Chứng chỉ',
            },
        ),
        migrations.CreateModel(
            name='DotThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.CharField(max_length=20, unique=True, verbose_name='Mã đợt thi')),
                ('ten_dot', models.CharField(max_length=200, verbose_name='Tên đợt thi')),
                ('thoi_gian_bat_dau', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu')),
                ('thoi_gian_ket_thuc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kết thúc')),
                ('file_thong_bao', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='File thông báo (PDF)')),
                ('diem_chuan_ngoai_ngu', models.FloatField(default=5.0, verbose_name='Điểm chuẩn Ngoại ngữ')),
                ('diem_liet_ngoai_ngu', models.FloatField(default=0.0, verbose_name='Điểm liệt Ngoại ngữ')),
                ('diem_chuan_tin_hoc', models.FloatField(default=5.0, verbose_name='Điểm chuẩn Tin học')),
                ('diem_liet_tin_hoc', models.FloatField(default=0.0, verbose_name='Điểm liệt Tin học')),
            ],
            options={
                'verbose_name': 'Đợt thi',
                'verbose_name_plural': '5. Cấu hình Đợt thi',
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa', models.CharField(max_length=200, unique=True, verbose_name='Tên Khoa/Viện')),
            ],
            options={
                'verbose_name': 'Danh mục Khoa',
                'verbose_name_plural': '1. Danh mục Khoa/Viện',
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=15, unique=True, verbose_name='Mã Sinh Viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và Tên')),
                ('lop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lớp sinh hoạt')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('email_truong', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email trường')),
                ('email_ca_nhan', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cá nhân')),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Ảnh đại diện')),
                ('khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_vien_list', to='students.khoa', verbose_name='Khoa/Viện')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ho_so', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinh Viên',
                'verbose_name_plural': '3. Quản lý Hồ sơ Sinh Viên',
            },
        ),
        migrations.CreateModel(
            name='LopBoiDuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('ten_lop', models.CharField(max_length=200, verbose_name='Tên lớp')),
                ('loai', models.CharField(choices=[('TA_TC', 'Tiếng Anh tăng cường'), ('TA_CDR', 'Ôn thi CĐR Ngoại ngữ'), ('TH_CDR', 'Ôn thi CĐR Tin học')], max_length=50, verbose_name='Loại lớp')),
                ('si_so_toi_da', models.IntegerField(default=40, verbose_name='Sĩ số tối đa')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang mở đăng ký')),
                ('file_import_excel', models.FileField(blank=True, null=True, upload_to='temp_imports/', verbose_name='Excel nạp SV')),
                ('can_bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sinh_vien', models.ManyToManyField(blank=True, related_name='lop_hoc', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Lớp bồi dưỡng',
                'verbose_name_plural': '7. Quản lý Lớp bồi dưỡng',
            },
        ),
        migrations.CreateModel(
            name='LichSuThi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mon_thi', models.CharField(choices=[('TA_DAU_VAO', 'Tiếng Anh đầu vào'), ('CDR_NGOAI_NGU', 'CĐR Ngoại ngữ'), ('CDR_TIN_HOC', 'CĐR Tin học')], max_length=20, verbose_name='Môn thi')),
                ('sbd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số báo danh')),
                ('ngay_thi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngày thi 1')),
                ('ca_thi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ca thi 1')),
                ('phong_thi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng thi 1')),
                ('ngay_thi_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngày thi Nói')),
                ('ca_thi_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ca thi Nói')),
                ('phong_thi_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng thi Nói')),
                ('diem_thanh_phan_1', models.FloatField(blank=True, null=True, verbose_name='Nghe / Trắc nghiệm')),
                ('diem_thanh_phan_2', models.FloatField(blank=True, null=True, verbose_name='Đọc / Thực hành')),
                ('diem_thanh_phan_3', models.FloatField(blank=True, null=True, verbose_name='Viết')),
                ('diem_thanh_phan_4', models.FloatField(blank=True, null=True, verbose_name='Nói')),
                ('diem_tong', models.FloatField(blank=True, null=True, verbose_name='Tổng điểm / Đánh giá')),
                ('xep_loai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xếp loại')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('ket_qua_dat', models.BooleanField(default=False, verbose_name='Kết quả Đạt')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('dot_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua', to='students.dotthi')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thi', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Điểm thi / Lịch thi',
                'verbose_name_plural': '6. Quản lý Điểm thi',
            },
        ),
        migrations.CreateModel(
            name='DangKyLop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_minh_chung', models.FileField(blank=True, null=True, upload_to='minh_chung_dk/%Y/%m/', verbose_name='Biên lai')),
                ('thoi_gian_dk', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký')),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('THANH_CONG', 'Đã duyệt'), ('DA_HUY', 'Đã hủy')], default='CHO_DUYET', max_length=20, verbose_name='Trạng thái')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_dang_ky', to='students.lopboiduong')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_dang_ky_lop', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Phiếu đăng ký',
                'verbose_name_plural': '8. Duyệt Đăng ký học',
                'unique_together': {('sinh_vien', 'lop_hoc')},
            },
        ),
        migrations.CreateModel(
            name='ChungChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hieu', models.CharField(help_text='Dùng để chuyên viên tra cứu hậu kiểm', max_length=100, verbose_name='Số hiệu / ID')),
                ('ngay_cap', models.DateField(verbose_name='Ngày cấp')),
                ('diem_tong', models.FloatField(blank=True, null=True, verbose_name='Điểm tổng')),
                ('diem_thanh_phan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Điểm thành phần (L/R/S/W)')),
                ('file_minh_chung', models.FileField(upload_to='minh_chung_chung_chi/%Y/%m/', verbose_name='File minh chứng')),
                ('trang_thai', models.CharField(choices=[('CHO', 'Chờ xét duyệt'), ('DAT', 'Hợp lệ (Đạt)'), ('KHONG_DAT', 'Từ chối (Không đạt)')], default='CHO', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu_xac_minh', models.TextField(blank=True, null=True, verbose_name='Ghi chú của Chuyên viên')),
                ('ngay_nop', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.danhmucchungchi', verbose_name='Loại chứng chỉ')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_chung_chi', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Hồ sơ Chứng chỉ',
                'verbose_name_plural': 'Hồ sơ Chứng chỉ',
                'unique_together': {('sinh_vien', 'so_hieu')},
            },
        ),
    ]
