# Generated by Django 4.2.29 on 2026-04-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=15, unique=True, verbose_name='Mã Sinh Viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và Tên')),
                ('khoa', models.CharField(max_length=100, verbose_name='Khoa Quản Lý')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('is_dat_cdr', models.BooleanField(default=False, verbose_name='Đạt Chuẩn Đầu Ra')),
            ],
            options={
                'verbose_name': 'Sinh Viên',
                'verbose_name_plural': 'Danh Sách Sinh Viên',
            },
        ),
    ]
