# Generated by Django 4.2.29 on 2026-04-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopBoiDuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('ten_lop', models.CharField(max_length=200, verbose_name='Tên lớp')),
                ('loai', models.CharField(choices=[('TATC', 'Tiếng Anh tăng cường'), ('CDR', 'Chuẩn đầu ra')], max_length=50, verbose_name='Loại lớp')),
                ('sinh_vien', models.ManyToManyField(related_name='lop_hoc', to='students.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='DiemThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_thi', models.CharField(max_length=100, verbose_name='Môn thi')),
                ('diem_so', models.FloatField(verbose_name='Điểm')),
                ('ngay_thi', models.DateField(verbose_name='Ngày thi')),
                ('is_dat', models.BooleanField(default=False, verbose_name='Kết quả đạt')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sinhvien')),
            ],
        ),
    ]
