# Generated by Codex on 2026-06-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TieuChiChuanDauRa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tieu_chi', models.CharField(max_length=255, verbose_name='Tên tiêu chí')),
                ('loai_chuan', models.CharField(choices=[('NGOAI_NGU', 'Chuẩn đầu ra Ngoại ngữ'), ('TIN_HOC', 'Chuẩn đầu ra Tin học')], max_length=20, verbose_name='Loại chuẩn')),
                ('pham_vi_loai_nganh', models.CharField(choices=[('ALL', 'Tất cả ngành'), ('THUONG', 'Ngành thông thường'), ('NGON_NGU_ANH', 'Ngôn ngữ Anh'), ('NGON_NGU_TRUNG', 'Ngôn ngữ Trung Quốc')], default='ALL', max_length=30, verbose_name='Phạm vi loại ngành')),
                ('pham_vi_chuong_trinh', models.CharField(choices=[('ALL', 'Tất cả chương trình'), ('DAI_TRA', 'Đại trà'), ('CHAT_LUONG_CAO', 'Chất lượng cao'), ('TIEN_TIEN', 'Tiên tiến'), ('KHAC', 'Khác')], default='ALL', max_length=30, verbose_name='Phạm vi chương trình đào tạo')),
                ('khoa_tuyen_sinh_tu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Khóa tuyển sinh từ')),
                ('khoa_tuyen_sinh_den', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Khóa tuyển sinh đến')),
                ('bac_ngoai_ngu_toi_thieu', models.PositiveSmallIntegerField(blank=True, help_text='Chỉ áp dụng cho chuẩn Ngoại ngữ.', null=True, verbose_name='Bậc ngoại ngữ tối thiểu')),
                ('thoi_han_hieu_luc_thang', models.PositiveSmallIntegerField(default=60, verbose_name='Thời hạn hiệu lực (tháng)')),
                ('so_chung_chi_mos_toi_thieu', models.PositiveSmallIntegerField(default=3, help_text='Chỉ áp dụng cho chuẩn Tin học.', verbose_name='Số module MOS tối thiểu')),
                ('uu_tien', models.PositiveSmallIntegerField(default=100, help_text='Số càng nhỏ thì càng được ưu tiên khi nhiều tiêu chí cùng khớp.', verbose_name='Độ ưu tiên')),
                ('ngay_hieu_luc_tu', models.DateField(blank=True, null=True, verbose_name='Hiệu lực từ ngày')),
                ('ngay_hieu_luc_den', models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến ngày')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Tiêu chí chuẩn đầu ra',
                'verbose_name_plural': '3. Cấu hình Tiêu chí chuẩn đầu ra',
                'ordering': ['loai_chuan', 'uu_tien', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CauHinhVaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('ADMIN', 'Quản trị hệ thống'), ('TRUNG_TAM', 'Cán bộ Trung tâm NN-TH'), ('KHOA', 'Quản lý khoa'), ('PHONG_BAN', 'Phòng ban liên quan'), ('GIANG_VIEN', 'Giảng viên'), ('CO_VAN', 'Cố vấn học tập'), ('SINH_VIEN', 'Sinh viên')], default='SINH_VIEN', max_length=20, verbose_name='Vai trò nghiệp vụ')),
                ('duoc_xem_toan_bo', models.BooleanField(default=False, verbose_name='Được xem toàn bộ dữ liệu')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('khoas_phu_trach', models.ManyToManyField(blank=True, related_name='nguoi_phu_trach', to='students.khoa', verbose_name='Các khoa phụ trách')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vai_tro_nghiep_vu', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Cấu hình vai trò',
                'verbose_name_plural': '0. Cấu hình Vai trò người dùng',
                'ordering': ['user__username'],
            },
        ),
    ]
