# Generated by Django 6.0.4 on 2026-05-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotthi',
            name='trang_thai',
        ),
    ]
