# Generated by Django 4.2.29 on 2026-04-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_lopboiduong_diemthi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='is_dat_cdr',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='is_dat_anh_van_dau_vao',
            field=models.BooleanField(default=False, verbose_name='Đạt Tiếng Anh đầu vào'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='is_dat_cdr_ngoai_ngu',
            field=models.BooleanField(default=False, verbose_name='Đạt CĐR Ngoại ngữ'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='is_dat_cdr_tin_hoc',
            field=models.BooleanField(default=False, verbose_name='Đạt CĐR Tin học'),
        ),
    ]
