# Generated by Django 4.2.29 on 2026-04-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_sinhvien_is_dat_cdr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='is_dat_anh_van_dau_vao',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='is_dat_cdr_ngoai_ngu',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='is_dat_cdr_tin_hoc',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='diem_anh_van_dau_vao',
            field=models.FloatField(default=0, verbose_name='Điểm TA đầu vào'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='diem_cdr_ngoai_ngu',
            field=models.FloatField(default=0, verbose_name='Điểm CĐR Ngoại ngữ'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='diem_cdr_tin_hoc',
            field=models.FloatField(default=0, verbose_name='Điểm CĐR Tin học'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_ngoai',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cá nhân'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_truong',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email trường'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='has_chung_chi_ngoai_ngu',
            field=models.BooleanField(default=False, verbose_name='Có chứng chỉ NN ngoài (IELTS/TOEIC...)'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='has_chung_chi_tin_hoc',
            field=models.BooleanField(default=False, verbose_name='Có chứng chỉ Tin học ngoài (MOS/IC3...)'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='is_mien_thi_dau_vao',
            field=models.BooleanField(default=False, verbose_name='Miễn thi TA đầu vào'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='lop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lớp'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='khoa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoa'),
        ),
    ]
