# Generated by Django 6.0.4 on 2026-07-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_role_scope_and_graduation_criteria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chungchi',
            options={'ordering': ['-ngay_nop'], 'verbose_name': 'Hồ sơ Chứng chỉ', 'verbose_name_plural': '5. Hồ sơ Chứng chỉ'},
        ),
        migrations.AlterModelOptions(
            name='danhmucchungchi',
            options={'ordering': ['loai', 'ten_chung_chi'], 'verbose_name': 'Danh mục Chứng chỉ', 'verbose_name_plural': '3. Danh mục Chứng chỉ'},
        ),
        migrations.AlterModelOptions(
            name='dotthi',
            options={'ordering': ['-thoi_gian_bat_dau'], 'verbose_name': 'Đợt thi', 'verbose_name_plural': '6. Cấu hình Đợt thi'},
        ),
        migrations.AlterModelOptions(
            name='khoa',
            options={'ordering': ['ma_khoa', 'ten_khoa'], 'verbose_name': 'Khoa', 'verbose_name_plural': '1. Danh mục Khoa'},
        ),
        migrations.AlterModelOptions(
            name='lichsuthi',
            options={'verbose_name': 'Điểm thi / Lịch thi', 'verbose_name_plural': '7. Quản lý Điểm thi'},
        ),
        migrations.AlterModelOptions(
            name='sinhvien',
            options={'ordering': ['-mssv'], 'verbose_name': 'Sinh Viên', 'verbose_name_plural': '4. Quản lý Hồ sơ Sinh Viên'},
        ),
        migrations.AddField(
            model_name='danhmucchungchi',
            name='bac',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Không xác định'), (1, 'Bậc 1'), (2, 'Bậc 2'), (3, 'Bậc 3'), (4, 'Bậc 4'), (5, 'Bậc 5'), (6, 'Bậc 6')], default=0, help_text='Chỉ áp dụng cho chứng chỉ Ngoại ngữ. 0 = không phân hạng.', verbose_name='Bậc tương ứng (Khung năng lực ngoại ngữ VN)'),
        ),
        migrations.AddField(
            model_name='khoa',
            name='ma_khoa',
            field=models.CharField(blank=True, help_text='VD: 100, 105, 401... dùng để xác định khoa từ MSSV', max_length=10, null=True, unique=True, verbose_name='Mã khoa'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='chuong_trinh_dao_tao',
            field=models.CharField(choices=[('DAI_TRA', 'Đại trà'), ('CHAT_LUONG_CAO', 'Chất lượng cao'), ('TIEN_TIEN', 'Tiên tiến'), ('KHAC', 'Khác')], default='DAI_TRA', max_length=30, verbose_name='Chương trình đào tạo'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='khoa_tuyen_sinh',
            field=models.PositiveSmallIntegerField(blank=True, help_text='VD: 69, 70, 71...', null=True, verbose_name='Khóa tuyển sinh'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='nam_du_kien_tot_nghiep',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm dự kiến tốt nghiệp'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='nam_nhap_hoc',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm nhập học'),
        ),
        migrations.AlterField(
            model_name='khoa',
            name='ten_khoa',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên khoa'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_vien_list', to='students.khoa', verbose_name='Khoa'),
        ),
        migrations.CreateModel(
            name='NganhDaoTao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nganh', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mã ngành')),
                ('ten_nganh', models.CharField(max_length=255, verbose_name='Tên ngành')),
                ('loai_nganh', models.CharField(choices=[('THUONG', 'Ngành thông thường'), ('NGON_NGU_ANH', 'Ngôn ngữ Anh'), ('NGON_NGU_TRUNG', 'Ngôn ngữ Trung Quốc')], default='THUONG', max_length=30, verbose_name='Loại ngành')),
                ('thoi_gian_dao_tao_nam', models.FloatField(default=4.0, help_text='VD: 4.0, 4.5, 5.0 năm', verbose_name='Thời gian đào tạo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_nganh', to='students.khoa', verbose_name='Khoa quản lý')),
            ],
            options={
                'verbose_name': 'Ngành đào tạo',
                'verbose_name_plural': '2. Danh mục Ngành đào tạo',
                'ordering': ['khoa__ma_khoa', 'ten_nganh'],
            },
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='nganh_dao_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_viens', to='students.nganhdaotao', verbose_name='Ngành đào tạo'),
        ),
        migrations.AddConstraint(
            model_name='nganhdaotao',
            constraint=models.UniqueConstraint(fields=('khoa', 'ten_nganh'), name='unique_nganh_theo_khoa'),
        ),
    ]
