# Generated by Django 4.2.29 on 2026-04-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_sinhvien_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_thi', models.CharField(choices=[('TA_DAU_VAO', 'Tiếng Anh đầu vào'), ('CDR_NGOAI_NGU', 'Chuẩn đầu ra Ngoại ngữ'), ('CDR_TIN_HOC', 'Chuẩn đầu ra Tin học')], max_length=20, verbose_name='Môn thi')),
                ('dot_thi', models.CharField(help_text='Ví dụ: Đợt 1 - Tháng 5/2026', max_length=100, verbose_name='Đợt thi')),
                ('diem_thi', models.FloatField(verbose_name='Điểm thi')),
                ('ghi_chu', models.TextField(blank=True, help_text='Ghi chú thêm nếu cần', null=True, verbose_name='Ghi chú')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày cập nhật hệ thống')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thi', to='students.sinhvien', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lịch sử thi',
                'verbose_name_plural': 'Lịch sử thi',
                'ordering': ['-ngay_cap_nhat'],
            },
        ),
    ]
