# Generated by Django 4.2.29 on 2026-04-02 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_lichsuthi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dot', models.CharField(help_text='VD: DOT1_052026', max_length=20, unique=True, verbose_name='Mã đợt thi')),
                ('ten_dot', models.CharField(help_text='VD: Đợt 1 - Tháng 5/2026', max_length=100, verbose_name='Tên đợt thi')),
                ('ngay_to_chuc', models.DateField(blank=True, null=True, verbose_name='Ngày tổ chức')),
                ('trang_thai', models.BooleanField(default=True, help_text='Bỏ tích nếu đợt thi đã đóng', verbose_name='Đang mở')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Danh mục Đợt thi',
                'verbose_name_plural': 'Danh mục Đợt thi',
                'ordering': ['-ngay_to_chuc'],
            },
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='dot_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_thi', to='students.dotthi', verbose_name='Đợt thi'),
        ),
    ]
