# Generated by Django 4.2.29 on 2026-04-02 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_dotthi_alter_lichsuthi_ngay_cap_nhat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChungChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('NGOAI_NGU', 'Ngoại ngữ'), ('TIN_HOC', 'Tin học')], max_length=20, verbose_name='Loại chứng chỉ')),
                ('ten_chung_chi', models.CharField(help_text='VD: IELTS 6.5, MOS Excel...', max_length=200, verbose_name='Tên chứng chỉ')),
                ('so_hieu', models.CharField(max_length=50, verbose_name='Số hiệu/Mã vạch')),
                ('ngay_cap', models.DateField(verbose_name='Ngày cấp')),
                ('file_minh_chung', models.FileField(upload_to='certificates/%Y/', verbose_name='Ảnh/PDF chứng chỉ')),
                ('trang_thai', models.CharField(choices=[('CHO', 'Chờ xác minh'), ('DAT', 'Đã xác minh (Đạt)'), ('KHONG_DAT', 'Không hợp lệ')], default='CHO', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu_xac_minh', models.TextField(blank=True, verbose_name='Ghi chú của cán bộ')),
            ],
            options={
                'verbose_name': 'Chứng chỉ sinh viên',
                'verbose_name_plural': 'Quản lý Chứng chỉ',
            },
        ),
        migrations.RemoveField(
            model_name='lopboiduong',
            name='sinh_vien',
        ),
        migrations.AlterModelOptions(
            name='dotthi',
            options={'verbose_name': 'Đợt thi', 'verbose_name_plural': 'Danh mục Đợt thi'},
        ),
        migrations.AlterModelOptions(
            name='lichsuthi',
            options={'verbose_name': 'Kết quả thi', 'verbose_name_plural': 'Kết quả các kỳ thi'},
        ),
        migrations.RemoveField(
            model_name='dotthi',
            name='ghi_chu',
        ),
        migrations.RemoveField(
            model_name='dotthi',
            name='ngay_to_chuc',
        ),
        migrations.RemoveField(
            model_name='lichsuthi',
            name='ghi_chu',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='diem_anh_van_dau_vao',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='diem_cdr_ngoai_ngu',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='diem_cdr_tin_hoc',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='email_ngoai',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='has_chung_chi_ngoai_ngu',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='has_chung_chi_tin_hoc',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='is_mien_thi_dau_vao',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='so_dien_thoai',
        ),
        migrations.AddField(
            model_name='dotthi',
            name='file_thong_bao',
            field=models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='File thông báo (PDF)'),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='thoi_gian_bat_dau',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='thoi_gian_ket_thuc',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='dotthi',
            name='ma_dot',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã đợt'),
        ),
        migrations.AlterField(
            model_name='dotthi',
            name='ten_dot',
            field=models.CharField(max_length=200, verbose_name='Tên đợt thi'),
        ),
        migrations.AlterField(
            model_name='dotthi',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Đang mở đăng ký'),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='dot_thi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua', to='students.dotthi'),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='mon_thi',
            field=models.CharField(choices=[('TA_DAU_VAO', 'Tiếng Anh đầu vào'), ('CDR_NGOAI_NGU', 'CĐR Ngoại ngữ'), ('CDR_TIN_HOC', 'CĐR Tin học')], max_length=20, verbose_name='Môn thi'),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thi', to='students.sinhvien'),
        ),
        migrations.DeleteModel(
            name='DiemThi',
        ),
        migrations.DeleteModel(
            name='LopBoiDuong',
        ),
        migrations.AddField(
            model_name='chungchi',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_chung_chi', to='students.sinhvien'),
        ),
    ]
