# Generated by Django 4.2.29 on 2026-04-02 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_chungchi_remove_lopboiduong_sinh_vien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopBoiDuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('ten_lop', models.CharField(max_length=200, verbose_name='Tên lớp')),
                ('loai', models.CharField(choices=[('TATC', 'Tiếng Anh tăng cường'), ('CDR', 'Ôn thi Chuẩn đầu ra')], max_length=50, verbose_name='Loại lớp')),
                ('si_so_toi_da', models.IntegerField(default=40, verbose_name='Sĩ số tối đa')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang mở đăng ký')),
                ('can_bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ phụ trách')),
                ('sinh_vien', models.ManyToManyField(blank=True, related_name='lop_hoc', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Lớp bồi dưỡng',
                'verbose_name_plural': '1. Quản lý Lớp bồi dưỡng',
            },
        ),
        migrations.CreateModel(
            name='DangKyLop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_dk', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký')),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('THANH_CONG', 'Đăng ký thành công'), ('DA_HUY', 'Đã hủy')], default='CHO_DUYET', max_length=20, verbose_name='Trạng thái')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_dang_ky', to='students.lopboiduong', verbose_name='Lớp học')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_dang_ky_lop', to='students.sinhvien', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Phiếu đăng ký học',
                'verbose_name_plural': '2. Quản lý Đăng ký học',
                'unique_together': {('sinh_vien', 'lop_hoc')},
            },
        ),
    ]
