# Generated by Django 4.2.29 on 2026-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_lopboiduong_dangkylop'),
    ]

    operations = [
        migrations.AddField(
            model_name='lopboiduong',
            name='file_import_excel',
            field=models.FileField(blank=True, help_text='Tải file Excel có cột "MSSV". Hệ thống tự động nạp sinh viên vào lớp khi lưu.', null=True, upload_to='temp_imports/', verbose_name='Upload File Excel nạp SV'),
        ),
        migrations.AlterField(
            model_name='chungchi',
            name='ghi_chu_xac_minh',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='chungchi',
            name='ten_chung_chi',
            field=models.CharField(max_length=200, verbose_name='Tên chứng chỉ'),
        ),
        migrations.AlterField(
            model_name='lopboiduong',
            name='loai',
            field=models.CharField(choices=[('TA_TC', 'Tiếng Anh tăng cường'), ('TA_CDR', 'Ôn thi CĐR Ngoại ngữ'), ('TH_CDR', 'Ôn thi CĐR Tin học')], max_length=50, verbose_name='Loại lớp'),
        ),
    ]
