# Generated by Django 4.2.29 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_lopboiduong_file_import_excel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dangkylop',
            options={},
        ),
        migrations.AddField(
            model_name='dangkylop',
            name='file_minh_chung',
            field=models.FileField(blank=True, null=True, upload_to='minh_chung_dk/%Y/%m/', verbose_name='Ảnh minh chứng (Biên lai)'),
        ),
    ]
