# Generated by Django 4.2.29 on 2026-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_dangkylop_options_dangkylop_file_minh_chung'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotthi',
            name='diem_chuan_ngoai_ngu',
            field=models.FloatField(default=5.0, verbose_name='Điểm chuẩn đạt Ngoại ngữ (Tổng)'),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_chuan_tin_hoc',
            field=models.FloatField(default=5.0, verbose_name='Điểm chuẩn đạt Tin học (Tổng)'),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_liet_ngoai_ngu',
            field=models.FloatField(default=0.0, help_text='Dưới mức này sẽ bị đánh rớt', verbose_name='Điểm liệt Ngoại ngữ (Mỗi phần)'),
        ),
        migrations.AddField(
            model_name='dotthi',
            name='diem_liet_tin_hoc',
            field=models.FloatField(default=0.0, verbose_name='Điểm liệt Tin học (Mỗi phần)'),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_thanh_phan_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm thành phần 1 (Lý thuyết/Máy tính)'),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='diem_thanh_phan_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm thành phần 2 (Thực hành/Phỏng vấn)'),
        ),
        migrations.AddField(
            model_name='lichsuthi',
            name='ket_qua_dat',
            field=models.BooleanField(default=False, verbose_name='Đạt chuẩn'),
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='diem_thi',
            field=models.FloatField(verbose_name='Điểm tổng'),
        ),
    ]
