# Generated by Django 4.2.29 on 2026-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_dotthi_diem_chuan_ngoai_ngu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dangkylop',
            options={'verbose_name': 'Phiếu đăng ký học', 'verbose_name_plural': '2. Quản lý Đăng ký học'},
        ),
        migrations.AlterField(
            model_name='lichsuthi',
            name='diem_thi',
            field=models.FloatField(blank=True, help_text='Bỏ trống để máy tự tính nếu có Điểm TP', null=True, verbose_name='Điểm tổng'),
        ),
    ]
