# Generated by Django 4.2.29 on 2026-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_dangkylop_options_alter_lichsuthi_diem_thi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email_ca_nhan',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cá nhân'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
