# Generated by Django 6.0.4 on 2026-05-28 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('show_on_navbar', models.BooleanField(default=False, verbose_name='Hiển thị trên menu')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Hiển thị trên trang chủ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Danh mục bài viết',
                'verbose_name_plural': 'Danh mục bài viết',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên liên kết')),
                ('image', models.ImageField(upload_to='cms/quicklinks/', verbose_name='Ảnh Banner nút')),
                ('url', models.CharField(max_length=500, verbose_name='Đường dẫn ngoài')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Liên kết nhanh',
                'verbose_name_plural': '2. Quản lý Quick Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề Banner')),
                ('image', models.ImageField(upload_to='cms/sliders/', verbose_name='Hình ảnh')),
                ('link_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link liên kết')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': '1. Quản lý Slider',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Đường dẫn')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bai_viet/', verbose_name='Ảnh đại diện')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bai_viet/dinh_kem/', verbose_name='Tài liệu đính kèm')),
                ('view_count', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('is_published', models.BooleanField(default=True, verbose_name='Xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-created_at'],
            },
        ),
    ]
