# Generated by Django 4.2.29 on 2026-04-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Đường dẫn (Slug)')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': '1. Quản lý Danh mục',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('summary', models.TextField(help_text='Hiển thị ở trang danh sách', max_length=500, verbose_name='Tóm tắt ngắn')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/images/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cms/attachments/%Y/%m/', verbose_name='File đính kèm (PDF/Docx)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('is_published', models.BooleanField(default=True, verbose_name='Cho phép hiển thị')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết / Thông báo',
                'verbose_name_plural': '2. Quản lý Bài viết',
                'ordering': ['-created_at'],
            },
        ),
    ]
