# Generated by Django 4.2.29 on 2026-04-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bỏ tích nếu muốn ẩn danh mục này khỏi thanh điều hướng bên phải', verbose_name='Hiển thị ra trang người dùng'),
        ),
    ]
