# Generated by Django 4.2.29 on 2026-04-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_navbar',
            field=models.BooleanField(default=False, help_text='Tick vào ô này để đưa danh mục lên thanh Menu ngang trên cùng', verbose_name='Hiển thị trên Menu chính'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị ở Sidebar'),
        ),
    ]
