# Generated by Django 4.2.29 on 2026-04-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_category_show_on_navbar_alter_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên liên kết')),
                ('url', models.URLField(verbose_name='Đường dẫn (URL)')),
                ('order', models.IntegerField(default=0, help_text='Số nhỏ hiển thị trước', verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Liên kết nhanh',
                'verbose_name_plural': '3. Quản lý Liên kết nhanh (Sidebar)',
                'ordering': ['order'],
            },
        ),
    ]
