# Generated by Django 4.2.29 on 2026-04-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='image',
            field=models.ImageField(blank=True, help_text='Nên dùng ảnh chữ nhật ngang (Ví dụ: 300x100px)', null=True, upload_to='cms/quicklinks/', verbose_name='Ảnh Banner'),
        ),
    ]
