# Generated by Django 4.2.29 on 2026-04-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_quicklink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Tick vào đây để tạo thành một khối lưới 4 bài viết dưới cùng Trang chủ', verbose_name='Thành khối riêng ở Trang chủ'),
        ),
    ]
