# Generated by Django 6.0.4 on 2026-04-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_category_show_on_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài viết', 'verbose_name_plural': '2. Quản lý Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['order'], 'verbose_name': 'Liên kết nhanh', 'verbose_name_plural': '3. Liên kết Sidebar'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Khối tin trang chủ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_navbar',
            field=models.BooleanField(default=False, verbose_name='Hiện trên Menu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/images/%Y/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='Tóm tắt ngắn'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/quicklinks/', verbose_name='Banner (300x100)'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
