# Generated by Django 6.0.4 on 2026-04-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_post_options_alter_quicklink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề Banner')),
                ('image', models.ImageField(upload_to='cms/sliders/', verbose_name='Hình ảnh (Khối thống nhất)')),
                ('link_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link liên kết')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': '1. Quản lý Slider',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['order'], 'verbose_name': 'Liên kết nhanh', 'verbose_name_plural': '2. Quản lý Quick Links'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='Hiện trang chủ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_navbar',
            field=models.BooleanField(default=True, verbose_name='Hiện menu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt ngắn'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='image',
            field=models.ImageField(upload_to='cms/quicklinks/', verbose_name='Ảnh Banner nút'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Đường dẫn ngoài'),
        ),
    ]
